

spring:
  datasource:
    # docker run --name calendar-db -p 5432:5432 -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres -d postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/master.xml
    drop-first: true
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8081